name: Building For Linux

on:
  #push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  BuildForUbuntu:
    name: '🐧 Build for Ubuntu'
    runs-on: ubuntu-latest
    env:
      NVIDA_DRIVER_URL: "https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-ubuntu2404-12-6-local_12.6.2-560.35.03-1_amd64.deb"
      NVIDA_DRIVER_FILE_NAME: "cuda-repo-ubuntu2404-12-6-local_12.6.2-560.35.03-1_amd64.deb"
      NVIDA_PIN_URL: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin"
      NVIDA_PIN_NAME: "cuda-ubuntu2404.pin"
      NVIDA_APT_NAME: "cuda-toolkit-12-6"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Cache Nvdia Driver'
      id: cache-nvdia
      uses: actions/cache@v4
      with:
        path: ${{ env.NVIDA_DRIVER_FILE_NAME }}
        key: ${{ runner.os }}-${{ env.NVIDA_DRIVER_FILE_NAME }}

    - name: Download Nvdia driver
      if: steps.cache-nvdia.outputs.cache-hit != 'true'
      run: wget ${{ env.NVIDA_DRIVER_URL }}
      
    - name: '🔧 Install Nvidia Driver'
      run: |
        wget ${{ env.NVIDA_PIN_URL }}
        sudo mv ${{ env.NVIDA_PIN_NAME }} /etc/apt/preferences.d/cuda-repository-pin-600
        sudo dpkg -i ${{ env.NVIDA_DRIVER_FILE_NAME }}
        sudo cp /var/cuda-repo-*-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install ${{ env.NVIDA_APT_NAME }}

    - name: '🏗️ Configure CMake'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: '🛠️ Build'
      run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - name: '📃 Output Current Files'
      run: ls -R

    - name: '🧩 Install dependencies'
      run: |
          sudo apt-get update
    
    - name: '📃 Output Current Files'
      run: ls -R

